import { promises as fs } from 'node:fs'
import path from 'node:path'
import type { Capability } from './capability.js'
import { PLUGIN_NAME } from './capability.js'

/** Directory the generated capability plugin is written to. */
export function pluginPath(squadDir: string): string {
  return path.join(squadDir, '.plugin')
}

/**
 * Write every capability's body out as a skill inside one local plugin.
 *
 * Skills have to exist on disk for the SDK to discover them, and a plugin is the only
 * way to point a session at a specific directory. Every agent loads the same plugin; the
 * per-agent `skills` allowlist is what actually scopes who can invoke which capability.
 */
export async function writeCapabilityPlugin(
  squadDir: string,
  capabilities: Iterable<Capability>,
): Promise<string> {
  const root = pluginPath(squadDir)
  // Rebuild from scratch so a removed or renamed capability does not linger as a skill.
  await fs.rm(root, { recursive: true, force: true })
  await fs.mkdir(path.join(root, '.claude-plugin'), { recursive: true })
  await fs.writeFile(
    path.join(root, '.claude-plugin', 'plugin.json'),
    JSON.stringify(
      {
        name: PLUGIN_NAME,
        version: '0.1.0',
        description: 'Capability skills generated by claude-squad. Edit .squad/capabilities/*.md instead of this directory.',
      },
      null,
      2,
    ) + '\n',
  )

  for (const capability of capabilities) {
    const dir = path.join(root, 'skills', capability.name)
    await fs.mkdir(dir, { recursive: true })
    const frontmatter = [
      '---',
      `name: ${capability.name}`,
      `description: ${JSON.stringify(capability.description)}`,
      '---',
      '',
    ].join('\n')
    await fs.writeFile(path.join(dir, 'SKILL.md'), frontmatter + capability.instructions + '\n', 'utf8')
  }

  return root
}
